import Head from "next/head";
import NavBar from "./components/molecules/NavBar"
import App from "./App";
import Footer from "./components/organisms/Footer";

export default function Index() {
  return (
    <>
      <Head>
        <title>Creativedog (Prueba Técnica)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/favicon.ico" />
      </Head>
      <div>
        <NavBar />
        <App />
        <Footer/>
      </div>
    </>
  );
}